#!/bin/bash

#set -euxo pipefail

export SB=${SB:-/home/pi/sb_production}

while true; do
    cd ${SB}
#    sudo git pull
    sudo chown -R pi:pi ${SB}
    ${SB}/utils/playa \
	 --joystick_mode=1 \
	 --joystick_service_interval_sec=0.0 \
	 --move_fast_duration_joystick_sec=0.0 \
	 $*
done
